### PR TITLE
fix: improve OSS Index Error Reporting

### LINKED ISSUE #7976: ossIndexRemoteErrorWarnOnly is true but maven is stopping for oss index access errors (HttpResponseException: status code: 407, reason phrase: Proxy Authorization Required)
I have setted 
`<ossIndexWarnOnlyOnRemoteErrors>true</ossIndexWarnOnlyOnRemoteErrors> `
(and also ossIndexUsername and ossIndexPassword) but the maven build stopped (_Finished: FAILURE_) with a connection ERROR, when I'm expecting only a warning.
Am I misundestanding something?

**Version of dependency-check used**
maven dependency check:
```
<groupId>org.owasp</groupId>
<artifactId>dependency-check-maven</artifactId>
<version>12.1.6</version>
```

**Log file**
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:12.1.6:check (default) on project xxxx: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] AnalysisException: Failed to request component-reports
[ERROR] caused by DownloadFailedException: https://ossindex.sonatype.org/api/v3/component-report - Server status: 407 - Server reason: Proxy Authorization Required
[ERROR] caused by HttpResponseException: status code: 407, reason phrase: Proxy Authorization Required
.................................
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf   xxxxxxxx
........
Finished: FAILURE

### PR DESCRIPTION
**Pull request by jeremylong**
## Description of Change

ODC was not properly reporting authorization error messages. Previously, it was looking for the message to end with 401 to report an authorization issue. However, the actual error message from the client is `Failed to request component-reports: https://ossindex.sonatype.org/api/v3/component-report - Server status: 401 - Server reason: Unauthorized`. As such, the check for 401 needed to be improved.

## Related issues

Best guess this is related to https://github.com/dependency-check/DependencyCheck/issues/7975 and possibly https://github.com/dependency-check/DependencyCheck/issues/7971

## Have test cases been added to cover the new functionality?

Yes

### CODE REVIEW

**Comment by stefano-1973** [comment]
For the issues #7976 shouldn't be managed in the code also the status code 407 ? (Proxy Authorization Required error)

**Comment by jeremylong** [comment]
The original code had a few paths that would end up throwing the exception without checking the warn only flag. The updated version doesn't - even though we aren't specifically checking for a 407 it won't hit a path that throws the exception if you configure warn only.

**Review by marcelstoer — APPROVED** [review]
LGTM

**Comment by defaultbranch** [comment]
Thanks @jeremylong for keeping the tool working!

File: core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java [hunk 1]
```diff
@@ -148,40 +148,45 @@ protected void analyzeDependency(final Dependency dependency, final Engine engin
...
-                    if (StringUtils.endsWith(message, "401")) {
-                        LOG.error("Invalid credentials for the OSS Index, disabling the analyzer");
-                        throw new AnalysisException("Invalid credentials provided for OSS Index", ex);
-                    } else if (StringUtils.endsWith(message, "403")) {
-                        LOG.error("OSS Index access forbidden, disabling the analyzer");
-                        throw new AnalysisException("OSS Index access forbidden", ex);
-                    } else if (StringUtils.endsWith(message, "429")) {
+                    if (StringUtils.contains(message, "401")) {
+                        if (warnOnly) {
+                            LOG.warn("Invalid credentials for theOSS Index, disabling the analyzer");
```
Comment (chadlwilson) [inline core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java]:
```suggestion
                            LOG.warn("Invalid credentials for the OSS Index, disabling the analyzer");
```

Nitpick.

File: core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java [hunk 2]
```diff
@@ -148,40 +148,45 @@ protected void analyzeDependency(final Dependency dependency, final Engine engin
                 try {
                     requestDelay();
                     reports = requestReports(engine.getDependencies());
-                } catch (TransportException ex) {
+                } catch (SocketTimeoutException e) {
```
Comment (chadlwilson) [inline core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java:151]: I understand that the previous code also only specifically looked at `SocketTimeoutException` but it occurs to me that there are probably a number of other `IOException`s which essentially relate to an issue with the remote. I guess they will be handled by the generic `catch (Exception ex)` block, and depends how many the client wraps with `TransportException` which is a bit messy to unpack. Still this is not 'worse ' :-)

**Review by chadlwilson — APPROVED** [review]

File: core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java (hunk 2 above)
Comment (jeremylong) [reply core/src/main/java/org/owasp/dependencycheck/analyzer/OssIndexAnalyzer.java:151]: The code was checking for a 401 inside the `TransportExceptions` - but it was not a transport exception so the code never worked. I agree, this isn't "worse" but we could do better.

**Review by chadlwilson — APPROVED** [review]
