### PR TITLE
3620 improve doc on experimental analyzers

### LINKED ISSUE #3620: analyzer.swift.package.resolved.enabled=true is missing from conf
Noticed that analyzer.swift.package.resolved.enabled=true is missing from dependencycheck.properties but doc says it is enabled. Is this a mistake?

https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/dependencycheck.properties
https://github.com/jeremylong/DependencyCheck/blob/125751267e5b8775c08451862fe1595c15493e3c/ant/src/site/markdown/configuration.md

PS
Took the project down, added this config and compiled the project but have some run time issues so not able to test my self. Access to https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta fails with some cert issues

### PR DESCRIPTION
**Pull request by nhumblot**
## Description of Change

Fix #3620 

The goal of this PR is to :
* Make it more explicit that experimental analyzers property must be enabled for an experimental analyzer to run
* Enforce analyzers keys are all listed in the `dependencycheck.properties` file to prevent any misunderstanding.

I did not updated the cli documentation because the options are disabling analyzers instead of enabling them. I thought the misunderstanding was not present in this case. Another reason is also that I couldn't come with a short but clear & explicit sentence like the other tools.

Any suggestion is welcomed. :slightly_smiling_face: 

## Have test cases been added to cover the new functionality?

*yes*

### CODE REVIEW

File: core/src/test/java/org/owasp/dependencycheck/analyzer/DependencyCheckPropertiesTest.java [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+
+        Class<?> superclass = clazz.getSuperclass();
+        while (superclass != Object.class) {
+            if (extendsAbstractAnalyzer(superclass)) {
+                return true;
+            }
+            superclass = superclass.getSuperclass();
+        }
+
+        return false;
```
Comment (aikebah) [inline core/src/test/java/org/owasp/dependencycheck/analyzer/DependencyCheckPropertiesTest.java]: Can be coded more concise as

return AbstractAnalyzer.class.isAssignableFrom(clazz)

Comment (nhumblot) [reply core/src/test/java/org/owasp/dependencycheck/analyzer/DependencyCheckPropertiesTest.java]: Thank you! I updated the code. :slightly_smiling_face:

Comment (nhumblot) [reply core/src/test/java/org/owasp/dependencycheck/analyzer/DependencyCheckPropertiesTest.java]: Looks like one job got stuck and cancelled. Is it possible to relaunch it please? :pray:

**Review by jeremylong — APPROVED** [review]
